### ISSUE TITLE
will this can be used for chess by just adding a ChessGame.py ?

### ISSUE THREAD

**Issue by Unimax** [gemasphi/alpha-zero-torch#1]
I was just wondering if I can use this for chess?

if so what are the changes needed.

thanks in advance.

**Comment by gemasphi** [comment]
Hey, 

First, you can you use it for chess. You'll need to add a class for the game and represent the policy as only a plane because that's how it it is currently implemented. If you want to use more planes to represent the policy, you'll need to make some small changes in the code. Or if you want to make some changes on how you represent the input for the network.

**HOWEVER**, chess is an incredibly complex game. The performance of this implementation isn't optimal as it isn't parallelized as in the paper.  Besides that, they used 5064 TPUs and trained for days to reach GM level at chess. 
If you still want to do it, I recommend you to use [this implementation](https://github.com/facebookincubator/Polygames).

This repository is more for didactic purposes than anything else.

**Comment by Unimax** [comment]
@gemasphi thanks a lot for a quick reply. appreciated for the help.
